- name: "destroy | Get the role ARN information"
  ansible.builtin.import_tasks: role-facts.yml

- name: "destroy | remove cluster resources"
  ansible.builtin.command:
    hcp destroy cluster aws \
    --name {{ name }} \
    --region {{ region }} \
    --infra-id {{ name }} \
    --base-domain {{ domain }} \
    --role-arn {{ hcp_role_arn }} \
    --sts-creds {{ sts_creds.dir }}/sts-creds.json \
    --destroy-cloud-resources
  args:
    executable: /usr/bin/bash
  when: destroy
  register: cluster_destroy

#- name: "destroy | remove cluster configurations from filesystem"
#  ansible.builtin.file:
#    state: absent
#    path: "{{ deployment_dir }}/{{ name }}"
#  when: destroy

