---
# tasks file for hcp
# Validate everything exists first
# 
- name: "validate  | check for oc binary"
  ansible.builtin.shell:
    cmd: which oc 
  register: oc 
  changed_when: false
  failed_when: oc.rc != 0  

- name: "validate | check for hcp binary"
  ansible.builtin.shell:
    cmd: which hcp
  register: hcp
  changed_when: false
  failed_when: hcp.rc != 0  

- name: "validate | check for existence of {{ pull_secret_path }}"
  ansible.builtin.stat:
    path: "{{ pull_secret_path }}"
  register: pullsecret

- name: "validate | fail if {{ pull_secret_path }} is not found"
  ansible.builtin.fail:
    msg: "{{ pull_secret_path }} must exist"
  when: pullsecret.stat.exists is not defined

# Create sts-creds directory
- name: "preflight | create directory for {{ sts_creds.dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ sts_creds.dir}}"
    owner: "{{lookup('ansible.builtin.env', 'USER')}}"
    mode: 0750

# Generate the STS token - the token lives for 12 hrs by default
- name: "preflight | Generate sts token"
  community.aws.sts_session_token:
  register: sts

# Create the session config from a template
- name: "preflight | Create session token config {{ sts_creds.dir }}/{{ sts_creds.file }}"
  ansible.builtin.copy:
    content: "{{lookup('ansible.builtin.template', './templates/sts-creds.json.j2')}}"
    dest: "{{ sts_creds.dir }}/{{ sts_creds.file }}"
    owner: "{{lookup('ansible.builtin.env', 'USER')}}"
    mode: '0600'

- name: Provision IAM Roles and Policies for HyperShift
  include_tasks: iam.yml
  when: create_iam

- name: Create Hosted Control Plane Resources
  include_tasks: hcp-create.yml
  when: create

- name: Destroy Hosted Control Plane Resources
  include_tasks: hcp-destroy.yml
  when: destroy
