# The iam.hcp_role_name must exist for this to succeed
- name: "IAM | Get the {{ hcp_role_name }} role ARN"
  amazon.aws.iam_role_info:
    name: "{{ iam.hcp_role_name }}"
  register: result

# Set the role ARN as a fact for reuse
- set_fact:
    hcp_role_arn: "{{ result.iam_roles|map(attribute='arn')|first }}"
